linters:
  disable-all: true   # 关闭其他linter
  enable:             # 下面是开启的linter列表
#    - stylecheck     # 变量名命名建议
    - deadcode        # 检测未使用的声明
    - gosimple        # 给出代简化代码建议
    - govet           # 检查Go源代码并报告可疑结构，例如，其参数与格式字符串不对齐的Printf调用
#    - ineffassign    # 检查无效赋值
#    - staticcheck    # 静态分析检查
    - structcheck     # 查找未使用的结构体字段
    - typecheck       # 对Go代码进行解析和类型检查
    - unused          # 检查Go代码中未使用的常量，变量，函数和类型
    - varcheck        # 查找未使用的全局变量和常量
#    - gofmt           # 检测是否格式化
#    - errcheck       # 检查错误是否被处理
    - bodyclose       # 检查httpclient是否关闭
#    - dogsled        # 太多空白标识符检查分配
#    - dupl           # 重复代码检查, 默认15行
    - exportloopref   # 检查指向重复变量的指针
#    - whitespace     # 用于检测前导和尾随空白的工具
#    - unparam        # 检测未使用的参数
    - unconvert       # 减少不必要的类型转换
#    - sqlclosecheck  # 检查sql.Rows和sql.Stmt是否关闭
#    - noctx          # 查找发送不带上下文的http请求
#    - nlreturn       # 返回需要换行
#    - cyclop         # 检查函数和包循环复杂度 // 默认为 10
#    - contextcheck    # 检查函数是否使用了额非继承的上下文
#    - gosec           # 检查源代码是否存在安全问题
#    - goconst         # 查找可替换为常量的重复字符串
#    - forcetypeassert # 查找强制断言类型
run:
  skip-files:
    - ".*_test.go$"
  skip-dirs:
    - main
    - scripts
    - tests
linters-settings:
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.13"
    # https://staticcheck.io/docs/options#checks
    checks: [ "all" ]
  errcheck:
    # report about not checking of errors in type assertions: `a := b.(MyStruct)`;
    # default is false: such cases aren't reported by default.
    check-type-assertions: false

    # report about assignment of errors to blank identifier: `num, _ := strconv.Atoi(numStr)`;
    # default is false: such cases aren't reported by default.
    check-blank: false
  govet:
    disable:
      - structtag
  stylecheck:
    # Select the Go version to target.
    # Default: 1.13
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022", "-SA1007"]