name: CI2
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint
    steps:
      - uses: actions/checkout@v2
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.18
#      - name: lint-run
#        run: golangci-lint run